update-binary: eliminate inconsistent sysroot handling

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -93,10 +93,10 @@ $bootmode || {
   mount /data;
   umountparts="$umountparts /data";
 }
-[ -e "/system/system/build.prop" ] && sysroot="system";
-[ -e "/system_root/system/build.prop" ] && sysroot="system_root";
-[ -e "/mnt/system/system/build.prop" ] && sysroot="mnt/system";
-[ -f "/$sysroot/system/build.prop" ] || abort "Could not find a ROM in /$sysroot";
+[ -e "/system/system/build.prop" ] && sysroot="/system";
+[ -e "/system_root/system/build.prop" ] && sysroot="/system_root";
+[ -e "/mnt/system/system/build.prop" ] && sysroot="/mnt/system";
+[ -f "$sysroot/system/build.prop" ] || abort "Could not find a ROM!";
 
 case "$(basename "$zipfile" | tr 'A-Z' 'a-z')" in
   *magisk*)
@@ -125,18 +125,18 @@ if [ -e "/data/adb/magisk" ] && [ "$forcemagisk" = "yes" ]; then
   }
 else
   if [ "$sysroot" ]; then
-    mount -o rw,remount /$sysroot;
-    mount -o rw,remount /$sysroot /$sysroot;
+    mount -o rw,remount $sysroot;
+    mount -o rw,remount $sysroot $sysroot;
   else
     mount -o rw,remount /system;
     mount -o rw,remount /system /system;
   fi;
-  root="/$sysroot";
+  root="${sysroot:-/}";
   magisk=no;
-  log "Mounted /$sysroot/system RW";
+  log "Mounted $sysroot/system RW";
 fi;
 
-sdk="$(grep "ro.build.version.sdk=" "/$sysroot/system/build.prop" | head -n1 | select_word 1 | cut -d= -f2)";
+sdk="$(grep "ro.build.version.sdk=" "$sysroot/system/build.prop" | head -n1 | select_word 1 | cut -d= -f2)";
 
 backupdir="/data/media/0/$modname";
 
@@ -211,17 +211,17 @@ debloat() {
 }
 
 shandle() {
-  for glob in /$sysroot/$1; do
+  for glob in $sysroot/$1; do
     target="$glob";
-    destination="/dev/tmp/backup/${target#/$sysroot/}";
+    destination="/dev/tmp/backup/${target#$sysroot/}";
     remove "$target" "$destination";
   done;
 }
 
 mhandle() {
-  for glob in /$sysroot/$1; do
+  for glob in $sysroot/$1; do
     target="$glob";
-    destination="$root/${target#/$sysroot/}";
+    destination="$root/${target#$sysroot/}";
     debloat "$target" "$destination";
   done;
 }
